ZeRoGerc/loudly

app/src/main/java/ly/loud/loudly/application/models/PeopleGetterModel.java
app/src/main/java/ly/loud/loudly/base/Networks.java

New annotation for network type

---

app/build.gradle
app/src/main/java/ly/loud/loudly/application/AppComponent.java
app/src/main/java/ly/loud/loudly/application/models/VKModel.java
app/src/main/java/ly/loud/loudly/ui/MainActivity.java
app/src/main/java/ly/loud/loudly/ui/PostsAdapter.java
app/src/main/java/ly/loud/loudly/ui/brand_new/BasePresenter.java
app/src/main/java/ly/loud/loudly/ui/brand_new/FeedActivity.java
app/src/main/java/ly/loud/loudly/ui/brand_new/FeedFragment.java
app/src/main/java/ly/loud/loudly/ui/brand_new/FeedPresenter.java
app/src/main/java/ly/loud/loudly/ui/brand_new/FeedView.java
app/src/main/java/ly/loud/loudly/ui/brand_new/views/FeedRecyclerView.java
app/src/main/res/layout/app_bar_feed.xml
app/src/main/res/layout/content_feed.xml
app/src/main/res/layout/content_main.xml
app/src/main/res/menu/main_menu.xml

- FeedPresenter load real post
- Small fix for VKModel

FeedActivity now using fragments

---

app/src/main/java/ly/loud/loudly/ui/brand_new/feed/FeedActivity.java
app/src/main/java/ly/loud/loudly/ui/brand_new/post/NewPostPresenter.java
app/src/main/java/ly/loud/loudly/ui/brand_new/views/AttachmentAdapter.java
app/src/main/java/ly/loud/loudly/ui/brand_new/views/TextPlusAttachmentsView.java
app/src/main/res/layout/image_layout.xml
app/src/main/res/layout/material_new_post_fragment.xml
app/src/main/res/values/dimens.xml

Post creation UI

---

app/.gitignore
app/src/androidTest/java/ly/loud/loudly/test/Generators.java
app/src/androidTest/java/ly/loud/loudly/util/database/AttachmentTest.java
app/src/androidTest/java/ly/loud/loudly/util/database/DatabaseTest.java
app/src/androidTest/java/ly/loud/loudly/util/database/DatabaseTestSuite.java
app/src/androidTest/java/ly/loud/loudly/util/database/DatabaseUtilsTest.java
app/src/androidTest/java/ly/loud/loudly/util/database/KeyTest.java
app/src/androidTest/java/ly/loud/loudly/util/database/LinksTest.java
app/src/androidTest/java/ly/loud/loudly/util/database/LocationTest.java
app/src/androidTest/java/ly/loud/loudly/util/database/PostTest.java
app/src/main/java/ly/loud/loudly/networks/Loudly/LoudlyWrap.java
app/src/main/java/ly/loud/loudly/new_base/LoudlyImage.java
app/src/main/java/ly/loud/loudly/new_base/SingleImage.java
app/src/main/java/ly/loud/loudly/new_base/SinglePost.java
app/src/main/java/ly/loud/loudly/new_base/plain/PlainImage.java
app/src/main/java/ly/loud/loudly/util/Equality.java
app/src/main/java/ly/loud/loudly/util/database/DatabaseUtils.java

Database fixed for new architecture
Added ignored tests

Database and new architecture

---

app/src/main/java/ly/loud/loudly/application/models/CoreModel.java
app/src/main/java/ly/loud/loudly/application/models/FacebookModel.java
app/src/main/java/ly/loud/loudly/application/models/GetterModel.java
app/src/main/java/ly/loud/loudly/application/models/InstagramModel.java
app/src/main/java/ly/loud/loudly/application/models/KeysModel.java
app/src/main/java/ly/loud/loudly/application/models/NetworkContract.java
app/src/main/java/ly/loud/loudly/application/models/PostLoadModel.java
app/src/main/java/ly/loud/loudly/application/models/PostUploadModel.java
app/src/main/java/ly/loud/loudly/application/models/VKModel.java
app/src/main/java/ly/loud/loudly/ui/FullPostInfoActivity.java
app/src/main/java/ly/loud/loudly/ui/brand_new/post/NewPostPresenter.java
app/src/main/java/ly/loud/loudly/util/ListUtils.java
app/src/main/java/ly/loud/loudly/util/Utils.java

- List replaced with SolidLists

SolidLists everywhere

---

app/src/androidTest/java/ly/loud/loudly/test/Generators.java
app/src/androidTest/java/ly/loud/loudly/util/database/StoredPostTest.java
app/src/main/java/ly/loud/loudly/base/interfaces/SingleNetworkElement.java
app/src/main/java/ly/loud/loudly/base/single/Comment.java
app/src/main/java/ly/loud/loudly/base/single/SingleImage.java
app/src/main/java/ly/loud/loudly/base/single/SinglePost.java
app/src/main/java/ly/loud/loudly/legacy_base/Link.java
app/src/main/java/ly/loud/loudly/legacy_base/MultipleNetwork.java
app/src/main/java/ly/loud/loudly/legacy_base/SingleNetwork.java
app/src/main/java/ly/loud/loudly/legacy_base/attachments/Image.java
app/src/main/java/ly/loud/loudly/legacy_base/attachments/LoudlyImage.java
app/src/main/java/ly/loud/loudly/legacy_base/says/Comment.java
app/src/main/java/ly/loud/loudly/legacy_base/says/LoudlyPost.java
app/src/main/java/ly/loud/loudly/legacy_base/says/Post.java
app/src/main/java/ly/loud/loudly/legacy_base/says/Say.java
app/src/main/java/ly/loud/loudly/networks/Facebook/FacebookModel.java
app/src/main/java/ly/loud/loudly/networks/Facebook/FacebookWrap.java
app/src/main/java/ly/loud/loudly/networks/Instagram/InstagramWrap.java
app/src/main/java/ly/loud/loudly/networks/VK/VKModel.java
app/src/main/java/ly/loud/loudly/networks/VK/VKWrap.java
app/src/main/java/ly/loud/loudly/util/Equality.java
app/src/main/java/ly/loud/loudly/util/database/DatabaseUtils.java

- Link class moved to legacy_base
- Links in new classes replaced with good old Strings

Look, ma, no Link

---

app/src/main/java/ly/loud/loudly/ui/adapters/FeedAdapter.java
app/src/main/java/ly/loud/loudly/ui/adapters/holders/ViewHolderPost.java
app/src/main/java/ly/loud/loudly/ui/feed/FeedFragment.java
app/src/main/java/ly/loud/loudly/ui/feed/FeedPresenter.java

UI for deleteion of post

---

app/src/main/java/ly/loud/loudly/ui/MainActivity.java
app/src/main/java/ly/loud/loudly/ui/adapters/AttachmentAdapter.java
app/src/main/java/ly/loud/loudly/ui/new_post/NetworkChooseAdapter.java
app/src/main/java/ly/loud/loudly/ui/new_post/NetworksChooseLayout.java
app/src/main/java/ly/loud/loudly/ui/new_post/NetworksChoosePresenter.java
app/src/main/java/ly/loud/loudly/ui/new_post/NetworksChooseView.java
app/src/main/java/ly/loud/loudly/ui/views/ScrimCoordinatorLayout.java
app/src/main/java/ly/loud/loudly/ui/views/ScrimLayoutDelegate.java
app/src/main/java/ly/loud/loudly/ui/views/TextPlusAttachmentsView.java
app/src/main/java/ly/loud/loudly/ui/views/VisibilitySaveStateFrameLayout.java
app/src/main/res/layout/app_bar_feed.xml
app/src/main/res/layout/material_new_post_fragment.xml
app/src/main/res/layout/network_choose_list_item.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

New post fixes

---

app/src/main/java/ly/loud/loudly/networks/facebook/FacebookClient.java
app/src/main/java/ly/loud/loudly/networks/facebook/FacebookModel.java
app/src/main/java/ly/loud/loudly/networks/facebook/entities/Paging.java
app/src/main/java/ly/loud/loudly/networks/vk/VKModel.java
app/src/main/java/ly/loud/loudly/util/NetworkUtils.java

- Now loaded posts don't duplicate

Posts loading olive fixed

---

app/src/main/java/ly/loud/loudly/base/entities/Person.java
app/src/main/java/ly/loud/loudly/legacy_base/says/Comment.java
app/src/main/java/ly/loud/loudly/networks/NetworkContract.java
app/src/main/java/ly/loud/loudly/networks/facebook/FacebookClient.java
app/src/main/java/ly/loud/loudly/networks/facebook/FacebookModel.java
app/src/main/java/ly/loud/loudly/networks/facebook/FacebookWrap.java
app/src/main/java/ly/loud/loudly/networks/instagram/InstagramModel.java
app/src/main/java/ly/loud/loudly/networks/instagram/InstagramWrap.java
app/src/main/java/ly/loud/loudly/networks/vk/VKModel.java
app/src/main/java/ly/loud/loudly/networks/vk/VKWrap.java
app/src/main/java/ly/loud/loudly/ui/adapters/FullPostInfoAdapter.java
app/src/main/java/ly/loud/loudly/ui/adapters/PeopleListAdapter.java
app/src/main/java/ly/loud/loudly/ui/adapters/holders/ViewHolderComment.java
app/src/main/java/ly/loud/loudly/ui/adapters/holders/ViewHolderPerson.java
app/src/main/java/ly/loud/loudly/ui/full_post/FullPostInfoFragment.java
app/src/main/java/ly/loud/loudly/ui/people_list/PeopleListFragment.java
app/src/main/java/ly/loud/loudly/util/Utils.java

- Added opening of user's page after click on it
- Complete update - both UI and background

Users' pages

---

app/src/main/java/ly/loud/loudly/application/models/PostLoadModel.java
app/src/main/java/ly/loud/loudly/ui/MainActivity.java
app/src/main/java/ly/loud/loudly/ui/adapters/FeedAdapter.java
app/src/main/java/ly/loud/loudly/ui/feed/FeedFragment.java
app/src/main/java/ly/loud/loudly/ui/feed/FeedPresenter.java
app/src/main/java/ly/loud/loudly/ui/new_post/NewPostFragment.java
app/src/main/java/ly/loud/loudly/ui/new_post/NewPostPresenter.java
app/src/main/java/ly/loud/loudly/ui/new_post/NewPostView.java
app/src/main/java/ly/loud/loudly/ui/views/FeedRecyclerView.java
app/src/main/java/ly/loud/loudly/util/AssertionsUtils.java
app/src/main/java/ly/loud/loudly/util/Utils.java
app/src/main/res/values/string-messages.xml
app/src/main/res/values/strings-error.xml
app/src/main/res/values/styles.xml

- Could be some optimizations in next requests

Make adapter to notify user about changes

---

app/src/main/java/ly/loud/loudly/application/AppComponent.java
app/src/main/java/ly/loud/loudly/application/AppModule.java
app/src/main/java/ly/loud/loudly/application/Loudly.java
app/src/main/java/ly/loud/loudly/application/models/LoadMoreStrategyModel.java
app/src/main/java/ly/loud/loudly/ui/MainActivity.java
app/src/main/java/ly/loud/loudly/ui/adapters/FeedAdapter.java
app/src/main/java/ly/loud/loudly/ui/feed/FeedFragment.java
app/src/main/java/ly/loud/loudly/ui/feed/FeedPresenter.java
app/src/main/java/ly/loud/loudly/ui/settings/SettingsFragment.java
app/src/main/java/ly/loud/loudly/ui/views/FeedRecyclerView.java
app/src/main/res/layout/content_feed.xml
app/src/main/res/xml/preferences.xml

- Need better place to invoke needMore.

Feed refresh layout + LoadMore

---

app/src/main/java/ly/loud/loudly/util/BasePresenter.java

New lightweight presenter

---

app/src/main/AndroidManifest.xml
app/src/main/java/ly/loud/loudly/application/AppComponent.java
app/src/main/java/ly/loud/loudly/application/AppModule.java
app/src/main/java/ly/loud/loudly/application/UpdateInfoService.java
app/src/main/java/ly/loud/loudly/application/models/GetterModel.java
app/src/main/java/ly/loud/loudly/application/models/InfoUpdateModel.java
app/src/main/java/ly/loud/loudly/application/models/PostDeleterModel.java
app/src/main/java/ly/loud/loudly/application/models/PostLoadModel.java
app/src/main/java/ly/loud/loudly/application/models/PostUploadModel.java
app/src/main/java/ly/loud/loudly/application/models/PostsDatabaseModel.java
app/src/main/java/ly/loud/loudly/base/entities/Event.java
app/src/main/java/ly/loud/loudly/base/entities/Info.java
app/src/main/java/ly/loud/loudly/base/multiple/LoudlyImage.java
app/src/main/java/ly/loud/loudly/base/multiple/LoudlyPost.java
app/src/main/java/ly/loud/loudly/networks/NetworkContract.java
app/src/main/java/ly/loud/loudly/networks/Networks.java
app/src/main/java/ly/loud/loudly/networks/facebook/FacebookClient.java
app/src/main/java/ly/loud/loudly/networks/facebook/FacebookModel.java
app/src/main/java/ly/loud/loudly/networks/instagram/InstagramModel.java
app/src/main/java/ly/loud/loudly/networks/vk/VKModel.java
app/src/main/java/ly/loud/loudly/ui/adapters/holders/ItemTypes.java
app/src/main/java/ly/loud/loudly/ui/auth/AuthFragment.java
app/src/main/java/ly/loud/loudly/util/RxUtils.java
app/src/main/java/ly/loud/loudly/util/database/KeysDbModule.java
app/src/main/java/ly/loud/loudly/util/database/PostDbHelper.java
app/src/main/java/ly/loud/loudly/util/database/PostDbModule.java
app/src/main/java/ly/loud/loudly/util/database/entities/StoredEvent.java

Added updating of post's info
- Services
- Exponential backoff
- Database
- Rx

Info updates

---

app/src/main/java/ly/loud/loudly/application/Loudly.java
app/src/main/java/ly/loud/loudly/application/UpdateInfoService.java
app/src/main/java/ly/loud/loudly/application/models/AuthModel.java
app/src/main/java/ly/loud/loudly/application/models/InfoUpdateModel.java
app/src/main/java/ly/loud/loudly/application/models/KeysModel.java
app/src/main/java/ly/loud/loudly/application/models/PostDeleterModel.java
app/src/main/java/ly/loud/loudly/application/models/PostLoadModel.java
app/src/main/java/ly/loud/loudly/application/models/PostUploadModel.java
app/src/main/java/ly/loud/loudly/application/models/PostsDatabaseModel.java
app/src/main/java/ly/loud/loudly/networks/NetworkContract.java
app/src/main/java/ly/loud/loudly/networks/facebook/FacebookModel.java
app/src/main/java/ly/loud/loudly/networks/instagram/InstagramModel.java
app/src/main/java/ly/loud/loudly/networks/vk/VKModel.java
app/src/main/java/ly/loud/loudly/ui/auth/AuthFragment.java

Completables

---

app/src/main/java/ly/loud/loudly/application/models/PostLoadModel.java
app/src/main/java/ly/loud/loudly/application/models/PostsDatabaseModel.java
app/src/main/java/ly/loud/loudly/util/database/entities/StoredEvent.java

Now updating of info returns new list of posts

Lists of updated posts

---

.travis.yml
app/build.gradle

- Downgrade of support lib due to bugs(

Fix for bottom sheet (support lib)

---

app/src/main/java/ly/loud/loudly/application/AppComponent.java
app/src/main/java/ly/loud/loudly/application/models/KeysModel.java
app/src/main/java/ly/loud/loudly/application/models/PostLoadModel.java
app/src/main/java/ly/loud/loudly/base/entities/Info.java
app/src/main/java/ly/loud/loudly/networks/facebook/FacebookModel.java
app/src/main/java/ly/loud/loudly/networks/instagram/InstagramClient.java
app/src/main/java/ly/loud/loudly/networks/instagram/InstagramClientModule.java
app/src/main/java/ly/loud/loudly/networks/instagram/InstagramModel.java
app/src/main/java/ly/loud/loudly/networks/instagram/entities/Caption.java
app/src/main/java/ly/loud/loudly/networks/instagram/entities/Counter.java
app/src/main/java/ly/loud/loudly/networks/instagram/entities/Data.java
app/src/main/java/ly/loud/loudly/networks/instagram/entities/Image.java
app/src/main/java/ly/loud/loudly/networks/instagram/entities/Images.java
app/src/main/java/ly/loud/loudly/networks/instagram/entities/InstagramComment.java
app/src/main/java/ly/loud/loudly/networks/instagram/entities/InstagramPerson.java
app/src/main/java/ly/loud/loudly/networks/instagram/entities/InstagramPost.java
app/src/main/java/ly/loud/loudly/networks/instagram/entities/Meta.java
app/src/main/java/ly/loud/loudly/networks/instagram/entities/Pagination.java
app/src/main/java/ly/loud/loudly/test_utils/InstagramClientTestImpl.java
app/src/main/java/ly/loud/loudly/test_utils/InstagramClientTestModule.java
app/src/main/java/ly/loud/loudly/test_utils/TestAppComponent.java
app/src/main/java/ly/loud/loudly/ui/feed/FeedPresenter.java

Added previous support for Instagram

Instagram support

---

app/src/main/AndroidManifest.xml
app/src/main/java/ly/loud/loudly/application/AppComponent.java
app/src/main/java/ly/loud/loudly/application/ConnectionStateBroadcastsReceiver.java
app/src/main/java/ly/loud/loudly/application/UpdateInfoService.java
app/src/main/java/ly/loud/loudly/application/models/InfoUpdateModel.java

- Updates now are restarted when network state changed

Listen to connection state

---

app/src/main/java/ly/loud/loudly/application/models/GetterModel.java
app/src/main/java/ly/loud/loudly/networks/NetworkContract.java
app/src/main/java/ly/loud/loudly/networks/facebook/FacebookModel.java
app/src/main/java/ly/loud/loudly/networks/instagram/InstagramClient.java
app/src/main/java/ly/loud/loudly/networks/instagram/InstagramModel.java
app/src/main/java/ly/loud/loudly/networks/instagram/entities/InstagramPost.java
app/src/main/java/ly/loud/loudly/networks/loudly/LoudlyModel.java
app/src/main/java/ly/loud/loudly/networks/vk/VKModel.java
app/src/main/java/ly/loud/loudly/test_utils/InstagramClientTestImpl.java
app/src/main/java/ly/loud/loudly/ui/adapters/FullPostInfoAdapter.java
app/src/main/java/ly/loud/loudly/ui/adapters/holders/ViewHolderComment.java
app/src/main/java/ly/loud/loudly/ui/full_post/FullPostInfoFragment.java
app/src/main/java/ly/loud/loudly/ui/full_post/FullPostInfoPresenter.java
app/src/main/java/ly/loud/loudly/ui/full_post/FullPostInfoView.java
app/src/main/res/layout/list_item_comment.xml

Open comment page after click of it

---

app/src/main/java/ly/loud/loudly/ui/MainActivity.java
app/src/main/java/ly/loud/loudly/ui/TitledFragment.java
app/src/main/java/ly/loud/loudly/ui/feed/FeedFragment.java
app/src/main/java/ly/loud/loudly/ui/feed/FeedPresenter.java
app/src/main/java/ly/loud/loudly/ui/feed/FeedView.java
app/src/main/java/ly/loud/loudly/ui/full_post/FullPostInfoFragment.java

- Now it's possible to select networks from sidebar

Filtering posts
